---
- name: Install davfs2 and add mountpoint for Mail.Cloud
  hosts: all
  become: true  # Necessary for modifying system files like /etc/ssh/sshd_config

  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes

    - name: Install davfs2
      apt:
        name: davfs2
        state: present

    - name: Add authentification credentials to "secrets" file
      ansible.builtin.lineinfile:
        path: /etc/davfs2/secrets
        line: 'https://webdav.cloud.mail.ru/ inf1nityml@mail.ru l7dLn8w8qSBMc0aqI03s'   # The desired line
        state: present

    - name: Add authentification credentials to "secrets" file
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: 'https://webdav.cloud.mail.ru /mnt/cloud davfs user,rw,uid=1000,gid=1001,_netdev,dir_mode=0770,file_mode=0770 0 0'   # The desired line
        state: present

    - name: Create folder for the mount
      ansible.builtin.file:
      path: /mnt/cloud
      state: directory
      owner: asmodeus
      group: media
      mode: '0775'
